/MG/geometry/detector GerdaArrayPhaseIIPlus

/run/initialize

/vis/viewer/set/autoRefresh false

# /vis/open OGLIQt
/vis/open RayTracer 1000x2200
/vis/scene/create

# add here the volumes to draw
/control/execute diodes-nostr5.mac
/control/execute holders.mac
/control/execute cables.mac
/control/execute inner-fibers-core.mac

/vis/sceneHandler/attach

/vis/viewer/zoom 2.7
/control/execute vis-settings.mac

/vis/viewer/flush
