#!/bin/bash

saved=`pwd`
cpus=`nproc`

rm -rf /tmp/mage-*

counter=1
for f in `ls draw-*.mac`; do

    outf="`echo $f | cut -f 1 -d '.'`.jpeg"

    if [[ ! -f "$outf" || "$f" -nt "$outf" ]]; then
        id=`cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 7 | head -n 1`
        tmpdir="/tmp/mage-$id"
        mkdir $tmpdir
        cp -R ./*.mac $tmpdir
        cd $tmpdir
        echo "INFO: queuing $f -> $outf"
        MaGe $tmpdir/$f > /dev/null 2>&1 \
            && cp $tmpdir/g4RayTracer.viewer-0_0000.jpeg $saved/$outf \
            && notify-send 'MaGe' "$outf file created" &
        cd $saved

        if [[ $counter == $cpus ]]; then
            echo "INFO: waiting for the following background jobs to end..."
            jobs
            for job in `jobs -rp`; do
                wait $job
            done
            counter=1
        else
            let counter++
        fi
    fi
done
