#!/usr/bin/env bash

\cd `git rev-parse --show-toplevel`
source .github/shell-utils.sh
update_progress_plot
git add .github

git status

echo -n "Commit and push? [y/n] "; read ans

if [ "$ans" == "y" ]; then
    git add .
    git commit -m "[`whoami`@`hostname`] `date`"
    git push origin master
fi

\cd - > /dev/null
